Encryption
QString Encryption::password
int Encryption::prime1
int Encryption::prime2
const int Encryption::systemPrime1
const int Encryption::systemPrime2
Encryption::Encryption()
QString Encryption::generatePassword(int)
Referenced by EncryptForm::~EncryptForm.
void Encryption::setPassword(QString)
Referenced by EncryptForm::~EncryptForm.
QString Encryption::getPassword()
Referenced by EncryptForm::~EncryptForm.
QString Encryption::encrypt(QString)
Referenced by EncryptForm::~EncryptForm.
QString Encryption::decrypt(QString)
Referenced by DecryptForm::~DecryptForm.
void Encryption::generateKeys(int, int)
Referenced by DecryptForm::~DecryptForm, EncryptForm::~EncryptForm.
int Encryption::getPrime1()
Referenced by EncryptForm::~EncryptForm.
int Encryption::getPrime2()
Referenced by EncryptForm::~EncryptForm.
int Encryption::getSysPrime1()
Referenced by DecryptForm::~DecryptForm, EncryptForm::~EncryptForm.
int Encryption::getSysPrime2()
Referenced by DecryptForm::~DecryptForm, EncryptForm::~EncryptForm.
int Encryption::isPrime(unsigned long long)
unsigned long long Encryption::getRandomPrime(int, int)
int Encryption::useEquation(int)
int Encryption::reverseEquation(int)