.TH "core.h" 3 "Fri Dec 23 2016" "Version 1.0.0.0" "Rahasa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <encryption\&.h>\fP
.br
\fC#include <QClipboard>\fP
.br
\fC#include <QApplication>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCore\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rahasa from the source code\&.
