.TH "DecryptForm" 3 "Fri Dec 23 2016" "Version 1.0.0.0" "Rahasa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DecryptForm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <decryptform\&.h>\fP
.PP
Inherits \fBQWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecryptForm\fP (\fBQWidget\fP *parent=0)"
.br
.ti -1c
.RI "\fB~DecryptForm\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QStringList \fBdataLine\fP"
.br
.ti -1c
.RI "QString \fBfileEx\fP"
.br
.ti -1c
.RI "QString \fBcreateD\fP"
.br
.ti -1c
.RI "QString \fBuserKey\fP"
.br
.ti -1c
.RI "QString \fBprime1\fP"
.br
.ti -1c
.RI "QString \fBprime2\fP"
.br
.ti -1c
.RI "QString \fBexpire\fP"
.br
.ti -1c
.RI "QString \fBmaxView\fP"
.br
.ti -1c
.RI "QString \fBviewC\fP"
.br
.ti -1c
.RI "QString \fBlastView\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file decryptform\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DecryptForm::DecryptForm (\fBQWidget\fP * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 7 of file decryptform\&.cpp\&.
.SS "DecryptForm::~DecryptForm ()"

.PP
Definition at line 12 of file decryptform\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QString DecryptForm::createD\fC [protected]\fP"

.PP
Definition at line 35 of file decryptform\&.h\&.
.SS "QStringList DecryptForm::dataLine\fC [protected]\fP"

.PP
Definition at line 33 of file decryptform\&.h\&.
.SS "QString DecryptForm::expire\fC [protected]\fP"

.PP
Definition at line 39 of file decryptform\&.h\&.
.SS "QString DecryptForm::fileEx\fC [protected]\fP"

.PP
Definition at line 34 of file decryptform\&.h\&.
.SS "QString DecryptForm::lastView\fC [protected]\fP"

.PP
Definition at line 42 of file decryptform\&.h\&.
.SS "QString DecryptForm::maxView\fC [protected]\fP"

.PP
Definition at line 40 of file decryptform\&.h\&.
.SS "QString DecryptForm::prime1\fC [protected]\fP"

.PP
Definition at line 37 of file decryptform\&.h\&.
.SS "QString DecryptForm::prime2\fC [protected]\fP"

.PP
Definition at line 38 of file decryptform\&.h\&.
.SS "QString DecryptForm::userKey\fC [protected]\fP"

.PP
Definition at line 36 of file decryptform\&.h\&.
.SS "QString DecryptForm::viewC\fC [protected]\fP"

.PP
Definition at line 41 of file decryptform\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rahasa from the source code\&.
