.TH "EncryptForm" 3 "Fri Dec 23 2016" "Version 1.0.0.0" "Rahasa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncryptForm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encryptform\&.h>\fP
.PP
Inherits \fBQWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEncryptForm\fP (\fBQWidget\fP *parent=0)"
.br
.ti -1c
.RI "\fB~EncryptForm\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file encryptform\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EncryptForm::EncryptForm (\fBQWidget\fP * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 7 of file encryptform\&.cpp\&.
.SS "EncryptForm::~EncryptForm ()"

.PP
Definition at line 16 of file encryptform\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rahasa from the source code\&.
