.TH "encryptform.cpp" 3 "Fri Dec 23 2016" "Version 1.0.0.0" "Rahasa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encryptform.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'encryptform\&.h'\fP
.br
\fC#include 'ui_encryptform\&.h'\fP
.br
\fC#include 'startup\&.h'\fP
.br
\fC#include 'QDebug'\fP
.br
\fC#include <QProcess>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Rahasa from the source code\&.
