.TH "main.cpp" 3 "Fri Dec 23 2016" "Version 1.0.0.0" "Rahasa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'startup\&.h'\fP
.br
\fC#include <QApplication>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 4 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Rahasa from the source code\&.
