.TH "StartUp" 3 "Fri Dec 23 2016" "Version 1.0.0.0" "Rahasa" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StartUp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <startup\&.h>\fP
.PP
Inherits \fBQWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStartUp\fP (\fBQWidget\fP *parent=0)"
.br
.ti -1c
.RI "\fB~StartUp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file startup\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StartUp::StartUp (\fBQWidget\fP * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 7 of file startup\&.cpp\&.
.SS "StartUp::~StartUp ()"

.PP
Definition at line 11 of file startup\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rahasa from the source code\&.
